#!/bin/bash

for VARIANT in mobile general
do
  DEST=resume/$VARIANT
  mkdir -p $DEST
  fop -param variant $VARIANT -c ./fop.xconf -xml resume.xml -xsl resume-pdf.xsl $DEST/Matthias_Ferber_resume.pdf
done
